---
#tasks for finding getting data into Json from netstat


- name: Crontab view
  shell: 'crontab -l'
  register: crontab


- name: Convert crontab output to Json
  crontab_tojson:
    crontab: "{{crontab.stdout_lines | to_json}}"
  register: result

- debug: msg="{{result}}"
